spring.application.name=meetings
spring.datasource.url=jdbc:postgresql://localhost:5432/meetings
spring.datasource.username=postgres
spring.datasource.password=adminsri

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true